//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLibraryService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int id { get; set; }
        public string ad_login { get; set; }
        public string ad_password { get; set; }
        public string ad_name { get; set; }
    }
}
