//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationsServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/MyLibraryService")]
    public partial class Reservation : object
    {
        
        private ReservationsServiceReference.Book BookField;
        
        private ReservationsServiceReference.Student StudentField;
        
        private System.Nullable<System.DateTime> dateOfReservField;
        
        private int idField;
        
        private System.Nullable<int> id_BookField;
        
        private System.Nullable<int> id_StudentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReservationsServiceReference.Book Book
        {
            get
            {
                return this.BookField;
            }
            set
            {
                this.BookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReservationsServiceReference.Student Student
        {
            get
            {
                return this.StudentField;
            }
            set
            {
                this.StudentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dateOfReserv
        {
            get
            {
                return this.dateOfReservField;
            }
            set
            {
                this.dateOfReservField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_Book
        {
            get
            {
                return this.id_BookField;
            }
            set
            {
                this.id_BookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_Student
        {
            get
            {
                return this.id_StudentField;
            }
            set
            {
                this.id_StudentField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/MyLibraryService")]
    public partial class Book : object
    {
        
        private System.Collections.ObjectModel.ObservableCollection<ReservationsServiceReference.Reservation> ReservationsField;
        
        private string authorField;
        
        private int idField;
        
        private System.Nullable<int> priceField;
        
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ReservationsServiceReference.Reservation> Reservations
        {
            get
            {
                return this.ReservationsField;
            }
            set
            {
                this.ReservationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/MyLibraryService")]
    public partial class Student : object
    {
        
        private System.Collections.ObjectModel.ObservableCollection<ReservationsServiceReference.Reservation> ReservationsField;
        
        private string cinField;
        
        private string firstNameField;
        
        private int idField;
        
        private string lastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ReservationsServiceReference.Reservation> Reservations
        {
            get
            {
                return this.ReservationsField;
            }
            set
            {
                this.ReservationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cin
        {
            get
            {
                return this.cinField;
            }
            set
            {
                this.cinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationsServiceReference.IReservationService")]
    public interface IReservationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/MakeReservation", ReplyAction="http://tempuri.org/IReservationService/MakeReservationResponse")]
        void MakeReservation(ReservationsServiceReference.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/MakeReservation", ReplyAction="http://tempuri.org/IReservationService/MakeReservationResponse")]
        System.Threading.Tasks.Task MakeReservationAsync(ReservationsServiceReference.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/RemoveReservation", ReplyAction="http://tempuri.org/IReservationService/RemoveReservationResponse")]
        void RemoveReservation(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/RemoveReservation", ReplyAction="http://tempuri.org/IReservationService/RemoveReservationResponse")]
        System.Threading.Tasks.Task RemoveReservationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetReservations", ReplyAction="http://tempuri.org/IReservationService/GetReservationsResponse")]
        System.Collections.ObjectModel.ObservableCollection<ReservationsServiceReference.Reservation> GetReservations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetReservations", ReplyAction="http://tempuri.org/IReservationService/GetReservationsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ReservationsServiceReference.Reservation>> GetReservationsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IReservationServiceChannel : ReservationsServiceReference.IReservationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ReservationServiceClient : System.ServiceModel.ClientBase<ReservationsServiceReference.IReservationService>, ReservationsServiceReference.IReservationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReservationServiceClient() : 
                base(ReservationServiceClient.GetDefaultBinding(), ReservationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IReservationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ReservationServiceClient.GetBindingForEndpoint(endpointConfiguration), ReservationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReservationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReservationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void MakeReservation(ReservationsServiceReference.Reservation reservation)
        {
            base.Channel.MakeReservation(reservation);
        }
        
        public System.Threading.Tasks.Task MakeReservationAsync(ReservationsServiceReference.Reservation reservation)
        {
            return base.Channel.MakeReservationAsync(reservation);
        }
        
        public void RemoveReservation(int id)
        {
            base.Channel.RemoveReservation(id);
        }
        
        public System.Threading.Tasks.Task RemoveReservationAsync(int id)
        {
            return base.Channel.RemoveReservationAsync(id);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ReservationsServiceReference.Reservation> GetReservations()
        {
            return base.Channel.GetReservations();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<ReservationsServiceReference.Reservation>> GetReservationsAsync()
        {
            return base.Channel.GetReservationsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReservationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReservationService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:49287/MyServices/ReservationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReservationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IReservationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReservationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IReservationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IReservationService,
        }
    }
}
